server:
  port: 8084
  servlet:
    context-path: /services/be/stream-service


spring:
  application:
    name: AUDIO-SERVICE

doc:
  api:
    path: /doc/api
    title: audio API
    description: Documentation for the audio API
    version: 1.0.0



